stages:
  - test
  - deploy

mypy-scan:
  image: python:3-slim-buster
  stage: test
  before_script:
    - pip3 install mypy
  after_script: []
  allow_failure: false
  script:
    - mypy downstream_fairness/ --ignore-missing-imports --install-types --non-interactive
  only:
    - merge_requests

run-unit-tests:
  image: python:3.8-buster
  stage: test
  before_script:
    - pip3 install -r ./requirements.txt
    - pip3 install -r ./test/requirements.txt
  after_script: []
  allow_failure: false
  script:
    - export PYTHONPATH=./
    - pytest test
  only:
    - merge_requests

validate-install:
  image: python:3.8-buster
  stage: test
  script:
    - pip install .
    - python -c "import downstream_fairness"  # replace with the name of your package
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

tag_with_version:
  stage: deploy
  before_script:
    - git config --global user.email "gitlab_ci@arthur.ai"
    - git config --global user.name "GitLab CI"
  script:
    - VERSION=$(cat downstream_fairness/version.py | grep -o '".*"' | sed 's/"//g')
    - git tag "$VERSION"
    - git tag
    - git push --tags https://private-token:$PRIVATE_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:$CI_DEFAULT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

push_to_nexus:
  variables:
    PIP_CONFIG_FILE: /root/pip.conf
  image: python:3-buster
  stage: deploy
  before_script:
    - cp pip.conf ~/pip.conf
    - |
      echo 'machine repository.arthur.ai
          login '"${NEXUS_REPOSITORY_USERNAME}"'
          password '"${NEXUS_REPOSITORY_PASSWORD}" >> ~/.netrc
    - pip install pyyaml twine
    - pip install --upgrade build
  script:
    - python -m build --sdist --wheel --outdir publish
    - twine upload --repository-url https://repository.arthur.ai/repository/pypi-local/ -u ${NEXUS_REPOSITORY_USERNAME} -p ${NEXUS_REPOSITORY_PASSWORD} --verbose publish/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

push_to_pypi:
  image: python:3-buster
  stage: deploy
  before_script:
    - pip install pyyaml twine
    - pip install --upgrade build
  script:
    - python -m build --sdist --wheel --outdir publish
    - twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} --verbose publish/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

push_to_github:
  image:
    name: alpine/git
    entrypoint: [""]
  stage: deploy
  script:
    - git remote add gh https://automator-arthur:$GITHUB_TOKEN@github.com/arthur-ai/downstream-fairness
    - git checkout $CI_COMMIT_BRANCH
    - git push gh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
